### ISSUE TITLE
[Suggestion] Support Meta Data

### ISSUE THREAD

**Issue by MasterEnderman** [quat1024/burninator#1]
I would like to suggest support for block meta data in the config file.

**Comment by quat1024** [comment]
what use case do you have?

mods really shouldn't be putting anything other than rotation/etc on metadata and I don't see why you'd want a west-facing piston to be hot but not an east facing one lol

**Comment by MasterEnderman** [comment]
the mod ceramics has multiple decorative building blocks, including a lava one and i want only that one to burn the player and not the others as they all share the same block id

**Comment by DWX12** [comment]
Same goes for multiple other mods like Biomes O Plenty, Chisel, Quark, etc.

So I second this request.

**Comment by quat1024** [comment]
Closing this since i don't do much modding on 1.12. anymore and it's no longer an issue in 1.16.
